name: Docker CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image for Ubuntu 24
      run: docker build --tag dotfiles-ubuntu24 --build-arg SKIP_PYENV=1 -f docker/ubuntu-24-lts/Dockerfile .
    - name: Build Docker image for Debian 12
      run: docker build --tag dotfiles-debian12 --build-arg SKIP_PYENV=1 -f docker/ubuntu-12-lts/Dockerfile .
